### ISSUE TITLE
[Help wanted] Failing to understand some concepts

### ISSUE THREAD

**Issue by see7e** [see7e/42-codespace-builder#1]
I've been having difficulties implementing this type of customized workflow, if anyone has any idea how to make this run efficiently, your help would be greatly appreciated. :)

```yml
name: Set Up Codespace

on:
  create:
    branches:
      - 42

jobs:
  create-codespace:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Create Codespace
        uses: see7e/42-codespace-builder@v1
```

---

Before this I was trying to implement something like:

```yml
name: Create Codespace on 42 branch creation

on:
  create:
    branches:
      - 42

jobs:
  create-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Create Codespace
        uses: microsoft/create-codespace-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .devcontainer.json
```

but later I've found that GH looks for some repo in `uses:` and this repo don't even exists resulting in:

```log
Current runner version: '[2](https://github.com/see7e/42-ft_printf/actions/runs/6492982162/job/17632993103#step:1:2).[3](https://github.com/see7e/42-ft_printf/actions/runs/6492982162/job/17632993103#step:1:3)09.0'
Operating System
  Ubuntu
  22.0[4](https://github.com/see7e/42-ft_printf/actions/runs/6492982162/job/17632993103#step:1:4).3
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20231001.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20231001.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F2023[10](https://github.com/see7e/42-ft_printf/actions/runs/6492982162/job/17632993103#step:1:11)01.1
Runner Image Provisioner
  2.0.[31](https://github.com/see7e/42-ft_printf/actions/runs/6492982162/job/17632993103#step:1:35)0.1
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action microsoft/create-codespace-action, repository not found
```
